# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-13 09:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_auto_20190113_0920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderbook',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
