# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-13 09:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_auto_20190113_0922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='orderbook',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
