# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-13 17:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_auto_20190113_0926'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderbook',
            name='price',
            field=models.IntegerField(default=1),
        ),
    ]
